const constants = {
    SET_ALL_POKEMONS: 'SET_ALL_POKEMONS',
    GET_ALL_POKEMONS: 'GET_ALL_POKEMONS',
    SET_FAVORITES: 'SET_FAVORITES',
    SET_IS_AUTHORIZED: 'SET_IS_AUTHORIZED',
    SET_MODAL_WINDOW_AUTHORIZATION_SHOW: 'SET_MODAL_WINDOW_AUTHORIZATION_SHOW'
  }
  
  export default constants;