const constants = {
    SET_ALL_POKEMONS: 'SET_ALL_POKEMONS',
    GET_ALL_POKEMONS: 'GET_ALL_POKEMONS',
    SET_SELECTED_POKEMONS: 'SET_SELECTED_POKEMONS',
    SET_FAVORITES: 'SET_FAVORITES',
    SET_IS_AUTHORIZED: 'SET_IS_AUTHORIZED',
    SET_MODAL_WINDOW_AUTHORIZATION_SHOW: 'SET_MODAL_WINDOW_AUTHORIZATION_SHOW',
    SET_SEARCH_INPUT_DATA: 'SEARCH_INPUT_DATA',
    SET_CONTENT_AMOUNT: 'SET_CONTENT_AMOUNT',
    SET_PAGE_NUMBER: 'SET_PAGE_NUMBER'
  }
  
  export default constants;